#!/bin/bash
##==============================================================================
##  Alias
##==============================================================================
# Enabling Alias expansion, to use them in vim
shell="bash"
# shellcheck disable=SC2009
if [[ $(ps -p $$ | grep sh | awk '{print $(NF)}') = "$shell" ]]; then
   shopt -s expand_aliases
fi

# Improving readability options with:
# - Color coding
# - Human readable
# - Nicer sorting/behavior
# - Avoid preexisting Alias prefixing \ to de command, just in case
# - Piping to less for long commands, can navigate with vim keys
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias tree='\tree --dirsfirst -C'
alias dmesg='\dmesg --color=auto --reltime --human --nopager --decode'
alias free='\free -mht'
alias du='\du -h'
alias df='\df -h'
alias sudo='\sudo '

# Setting Alias for enhanced commands
alias ls='better_ls'
alias history='better_history'

# Add an "alert" Alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Setting Alias for git, to manage dotfiles in $HOME with autocomplete
## git use __git_main for autocomplete git subcommands are _git_subcomand
alias gitdot='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias gitdotsm='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME submodule'
alias gitdotsma='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME submodule add'
alias gitdotsmu='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME submodule update --remote --merge'
alias gitrdot='/usr/bin/git --git-dir=$HOME/.juanito_rconfig/.cfg/ --work-tree=$HOME/.juanito_rconfig'
alias gitrdotsm='/usr/bin/git --git-dir=$HOME/.juanito_rconfig/.cfg/ --work-tree=$HOME/.juanito_rconfig submodule'
alias gitrdotsma='/usr/bin/git --git-dir=$HOME/.juanito_rconfig/.cfg/ --work-tree=$HOME/.juanito_rconfig submodule add'
alias gitrdotsmu='/usr/bin/git --git-dir=$HOME/.juanito_rconfig/.cfg/ --work-tree=$HOME/.juanito_rconfig submodule update --remote --merge'
alias sshdot='/usr/bin/git --git-dir=$HOME/.sshcfg/ --work-tree=$HOME/.ssh'
# shellcheck disable=SC2009
if [[ $(ps -p $$ | grep sh | awk '{print $(NF)}') = "$shell" ]]; then
    if [ -f "/usr/share/bash-completion/completions/git" ]; then
        # shellcheck disable=SC1091
        . /usr/share/bash-completion/completions/git
        __git_complete sshdot __git_main
        __git_complete gitdot __git_main
        __git_complete gitdotsm _git_submodule
        __git_complete gitdotsma _git_submodule
        __git_complete gitdotsmu _git_submodule
        __git_complete gitrdot __git_main
        __git_complete gitrdotsm _git_submodule
        __git_complete gitrdotsma _git_submodule
        __git_complete gitrdotsmu _git_submodule
   fi
fi

# Tmux Alias
alias tls='tmux ls'
alias tks='tmux kill-session -t'
alias tkw='tmux kill-window -t'

# Reload rc files local/remote
alias rrc='source ~/.bashrc'
alias zrc='source ~/.zshrc'
alias trc='tmux source-file ~/.tmux.conf'
alias rrrc='source ~/.juanito_rconfig/.bashrc'
alias rtrc='tmux source-file ~/.juanito_rconfig/.tmux.conf'

# Vim Alias for remote instaces
alias rvim='vim -u $HOME/.juanito_rconfig/.vim/vimrc'

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../..'
alias .5='cd ../../../..'
alias .6='cd ../../../../..'
